### ISSUE TITLE
Unable to fetch repo

### ISSUE THREAD

**Issue by jribal** [mt7-dev/local_manifests#2]
Hi, I could not fetch the project.

I create a .repo dir and git clone then I used **repo sync** as in readme.md, but I get:
 error: command 'sync' requires repo to be installed first.
         Use "repo init" to install it here.

So i tried to set up the repo with : 
**repo init -u https://github.com/mt7-dev/local_manifests.git -b aosp-6.0.0_r1 -m mt7-dev.xml**

And i get :
Get https://github.com/mt7-dev/local_manifests.git
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
and
fatal: manifest 'mt7-dev.xml' not available
fatal: remove-project element specifies non-existent project: platform/frameworks/opt/telephony

I also tried without -m option and I get :
fatal: manifest 'default.xml' not available
fatal: manifest default.xml not found

I could init other repos but not yours.
Can you point me to the right way to init your repo please?

**Comment by gabrielepmattia** [comment]
> error: command 'sync' requires repo to be installed first.

You should do repo sync on your aosp source root directory after you copied mt7-dev.xml in .repo/local_manifests

**Comment by jribal** [comment]
I forgot to get the android sources.
repo init -u https://android.googlesource.com/platform/manifest -b android-6.0.0_r1
