### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ghost** [mt7-dev/local_manifests#3]
Steps:
- I got the Android sources for 6.0.0-r1
- git cloned local_manifests in .repo
- standard build: 
  - . build/envsetup.sh
  - lunch
  - make

Log: https://gist.github.com/georgenetu/776a070c90674baaa436af2c40de4249

**Comment by gabrielepmattia** [comment]
Why do I see `PLATFORM_VERSION=6.0.1`?

**Comment by ghost** [comment]
Indeed, I messed up at the 6.0.0.(r)1 part. Thanks for the help.
